main_tweets_homepage:
    path:     /main/tweets/{page}
    defaults: { _controller: MainTweetsBundle:Default:index, page: 1 }
    requirements:
        page: '\d+'

main_tweets_with_hash_tag:
    path:     /main/tweets/{hashtag}/{page}
    defaults: { _controller: MainTweetsBundle:Default:index, page: 1}
    requirements:
        page: '\d+'
